### ISSUE TITLE
Error executing examples in macOS

### ISSUE THREAD

**Issue by avelad** [google/shaka-streamer#35]
macOS Mojave (10.14.6 (18G95))
Python 3.7.4

python3 shaka-streamer -i config_files/input_vod_config.yaml -p config_files/pipeline_vod_config.yaml
```
shaka-streamer:86: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  input_config_dict = yaml.load(f)
shaka-streamer:88: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  pipeline_config_dict = yaml.load(f)
Traceback (most recent call last):
  File "shaka-streamer", line 111, in <module>
    sys.exit(main())
  File "shaka-streamer", line 101, in main
    bitrate_config_dict, args.cloud_url):
  File "/Users/alvaro.velad/workspace/shaka-streamer/streamer/controller_node.py", line 136, in start
    input_config = InputConfig(input_config_dict)
  File "/Users/alvaro.velad/workspace/shaka-streamer/streamer/configuration.py", line 243, in __init__
    value = self._check_and_convert_type(field, key, value)
  File "/Users/alvaro.velad/workspace/shaka-streamer/streamer/configuration.py", line 295, in _check_and_convert_type
    return [self._check_and_convert_type(subfield, key, v) for v in value]
  File "/Users/alvaro.velad/workspace/shaka-streamer/streamer/configuration.py", line 295, in <listcomp>
    return [self._check_and_convert_type(subfield, key, v) for v in value]
  File "/Users/alvaro.velad/workspace/shaka-streamer/streamer/configuration.py", line 282, in _check_and_convert_type
    sub_object = field.type(value)
  File "/Users/alvaro.velad/workspace/shaka-streamer/streamer/input_configuration.py", line 177, in __init__
    self.is_interlaced = autodetect.get_interlaced(self)
  File "/Users/alvaro.velad/workspace/shaka-streamer/streamer/autodetect.py", line 72, in get_interlaced
    interlaced_string = _probe(input, 'stream=field_order')
  File "/Users/alvaro.velad/workspace/shaka-streamer/streamer/autodetect.py", line 59, in _probe
    output_bytes = subprocess.check_output(command, stderr=subprocess.DEVNULL)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ffprobe', 'Sintel.2010.4k.mkv', '-select_streams', 'v:0', '-show_entries', 'stream=field_order', '-of', 'compact=p=0:nk=1']' returned non-zero exit status 1.

```

**Comment by joeyparrish** [comment]
I see a few different issues here.

1. You're missing ffprobe, which should have a more explicit error upfront.  We'll fix that.
2. YAMLLoadWarning doesn't occur on my packaged version of pyyaml in Ubuntu, so I will need to update our usage of pyyaml to avoid that warning on newer versions.

**Comment by avelad** [comment]
MAD00335-Velad:shaka-streamer alvaro.velad$ +ffprobe
-bash: +ffprobe: command not found

**Comment by joeyparrish** [comment]
Without the "+", please, and with all the arguments afterward.  Here's what I mean:

![txBvEx33jxB](https://user-images.githubusercontent.com/6843156/67023995-87880d80-f0b8-11e9-9d9a-888a85b41fc6.png)

**Comment by avelad** [comment]
I reinstalled ffmpeg with brew and now it works... It's very strange.. 

Thanks for your help!

**Comment by joeyparrish** [comment]
Happy to help!
